CREATE SCHEMA `db_101` ;
USE db_101;


CREATE TABLE GOALTYPE
(
	ID varchar(36) PRIMARY KEY NOT NULL,
    GOALTYPECODE VARCHAR(1)  NOT NULL,
	GOALTYPE VARCHAR (50) NOT NULL
);

INSERT INTO GOALTYPE (ID, GOALTYPECODE, GOALTYPE) VALUES (uuid(), 'A', 'Recovery');
INSERT INTO GOALTYPE (ID, GOALTYPECODE, GOALTYPE) VALUES (uuid(), 'B', 'Endurance Train');
INSERT INTO GOALTYPE (ID, GOALTYPECODE, GOALTYPE) VALUES (uuid(), 'C', 'Aerobic Capacity');
INSERT INTO GOALTYPE (ID, GOALTYPECODE, GOALTYPE) VALUES (uuid(), 'D', 'Lactate Threshold');
INSERT INTO GOALTYPE (ID, GOALTYPECODE, GOALTYPE) VALUES (uuid(), 'E', 'VO2');

CREATE TABLE BIKE
(
	ID varchar(36) PRIMARY KEY NOT NULL,
    BROKER VARCHAR(100)  NOT NULL,
	PORTNUMBER int NOT NULL,
    URL VARCHAR(2083)
);

INSERT INTO BIKE (ID, BROKER, PORTNUMBER, URL) VALUES ('3fe58f39-81fa-4872-bc84-c77991e9bd0f', '127.0.0.1', 1883, 'http://127.0.0.1:3141');

CREATE TABLE `USER`
(
	ID varchar(36) PRIMARY KEY NOT NULL,
	FIRSTNAME VARCHAR (50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    AGE INT NOT NULL,
    GENDER VARCHAR(10),
    WEIGHT DOUBLE NOT NULL,
    GOALTYPEID varchar(36) NOT NULL,
    LEVELOFFITNESS INT NOT NULL,
    USERTELEGRAMID VARCHAR(15) NOT NULL,
    FRIENDTELEGRAMID VARCHAR(15) NOT NULL,
    FOREIGN KEY (GOALTYPEID) REFERENCES GOALTYPE(ID),
    UNIQUE INDEX `EMAIL` (`EMAIL`)
);

DELIMITER $$

CREATE TRIGGER check_trigger
  BEFORE INSERT
  ON `USER`
  FOR EACH ROW
	BEGIN
		IF new.ID IS NULL THEN
			SET new.ID = uuid();
		END IF;
        IF new.LEVELOFFITNESS <= 0 or new.LEVELOFFITNESS > 5 THEN
			CALL `Error: Wrong values for fitness level`;
		END IF;
	END$$

DELIMITER ;

CREATE TABLE TRIP
(
	ID varchar(36) PRIMARY KEY NOT NULL,
	USERID VARCHAR (36) NOT NULL,
    `DATETIME` datetime NOT NULL,
    AVERAGESPEED DOUBLE NOT NULL,
    AVERAGEHEARTRATE DOUBLE NOT NULL,
    MAXSPEED DOUBLE NOT NULL,
    MAXHEARTRATE DOUBLE NOT NULL,
    MINHEARTRATE DOUBLE NOT NULL,
    HEARTRATEPLOT nvarchar(2083) NOT NULL,
    SPEEDPLOT nvarchar(2083) NOT NULL,
    MAP nvarchar(2083) NOT NULL,
    FOREIGN KEY (USERID) REFERENCES `USER`(ID)
);

DELIMITER $$

CREATE TRIGGER check_trigger_trip
  BEFORE INSERT
  ON TRIP
  FOR EACH ROW
	BEGIN
		IF new.ID IS NULL THEN
			SET new.ID = uuid();
		END IF;
	END$$

DELIMITER ;
	
  