USE db_101;

DROP PROCEDURE IF EXISTS USP_USER_LOGIN;
DELIMITER //
CREATE PROCEDURE USP_USER_LOGIN(
 IN PASSWORD varchar(100),
 IN EMAIL varchar(100),
 OUT OUTPUT JSON
)
BEGIN
DECLARE VALIDUSER BOOL;
DECLARE USERID varchar(36);

SET VALIDUSER = 0;


SELECT  1, `USER`.ID FROM `USER` WHERE `USER`.EMAIL = EMAIL AND  `USER`.PASSWORD = PASSWORD INTO VALIDUSER,USERID;

IF VALIDUSER = 1 AND USERID IS NOT NULL THEN
      SELECT JSON_MERGE_PRESERVE(
       JSON_OBJECT('id', `USER`.ID),
       JSON_OBJECT('first_name', FIRSTNAME),
       JSON_OBJECT('last_name', LASTNAME),
       JSON_OBJECT('name', CONCAT(FIRSTNAME,LASTNAME)),
       JSON_OBJECT('email', EMAIL),
       JSON_OBJECT('age', AGE),
       JSON_OBJECT('gender', GENDER),
       JSON_OBJECT('weight', WEIGHT),
       JSON_OBJECT('goal', GOALTYPE.GOALTYPECODE),
       JSON_OBJECT('goal_name', GOALTYPE.GOALTYPE),
       JSON_OBJECT('level_of_fitness', LEVELOFFITNESS),
       JSON_OBJECT('telegram_ID_user', USERTELEGRAMID),
       JSON_OBJECT('telegram_ID_friend', FRIENDTELEGRAMID)
    ) FROM `USER` inner join GOALTYPE on GOALTYPE.ID =  `USER`.GOALTYPEID
    WHERE `USER`.ID = USERID INTO OUTPUT;
ELSE
      SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Incorrect password/email';
END IF;

END
//
DELIMITER ;