USE db_101;

DROP PROCEDURE IF EXISTS USP_GET_TRIPS;
DELIMITER //
CREATE PROCEDURE USP_GET_TRIPS(
IN USERID VARCHAR (36),
OUT OUTPUT JSON
)
BEGIN

DECLARE TRIPS JSON;

SELECT JSON_ARRAYAGG(JSON_OBJECT('id', ID, 'datetime', `DATETIME`)) from TRIP where TRIP.USERID = USERID into TRIPS;

SELECT JSON_OBJECT('trips', TRIPS) INTO OUTPUT;


END
//
DELIMITER ;