USE db_101;

DROP PROCEDURE IF EXISTS USP_GET_TRIP_BY_ID;
DELIMITER //
CREATE PROCEDURE USP_GET_TRIP_BY_ID(
IN TRIPID VARCHAR (36),
IN USERID VARCHAR (36),
OUT OUTPUT JSON
)
BEGIN
DECLARE VALIDTRIP BOOL;

SET VALIDTRIP = 0;

SELECT 1 FROM TRIP WHERE TRIP.ID = TRIPID into VALIDTRIP;

IF VALIDTRIP = 1 AND TRIPID IS NOT NULL THEN
      SELECT JSON_MERGE_PRESERVE(
       JSON_OBJECT('id', ID),
       JSON_OBJECT('user_id', USERID),
       JSON_OBJECT('datetime', `DATETIME`),
       JSON_OBJECT('avg_speed', AVERAGESPEED),
       JSON_OBJECT('avg_heart_rate', AVERAGEHEARTRATE),
       JSON_OBJECT('max_speed', MAXSPEED),
       JSON_OBJECT('max_heart_rate', MAXHEARTRATE),
       JSON_OBJECT('min_heart_rate', MINHEARTRATE),
       JSON_OBJECT('heart_rate_plot', HEARTRATEPLOT),
       JSON_OBJECT('speed_plot', SPEEDPLOT),
       JSON_OBJECT('map', MAP)
    ) FROM TRIP WHERE TRIP.ID = TRIPID AND TRIP.USERID = USERID INTO OUTPUT;
ELSE
      SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Trip Not Found';
END IF;

END
//
DELIMITER ;