USE db_101;

DROP PROCEDURE IF EXISTS USP_SAVE_USER;
DELIMITER //
CREATE PROCEDURE USP_SAVE_USER(
 IN FIRSTNAME varchar(50),
 IN LASTNAME varchar(50),
 IN PASSWORD varchar(100),
 IN EMAIL varchar(100),
 IN AGE varchar(5),
 IN GENDER varchar(10),
 IN WEIGHT varchar(10),
 IN GOAL varchar(100),
 IN GOALTYPECODE varchar(1),
 IN LEVELOFFITNESS varchar(1),
 IN USERTELEGRAMID varchar(15),
 IN FRIENDTELEGRAMID varchar(15),
 OUT OUTPUT JSON
)
BEGIN
DECLARE GOALTYPEID VARCHAR(36);
DECLARE ID VARCHAR(36);

SELECT GOALTYPE.ID FROM GOALTYPE WHERE GOALTYPE.GOALTYPECODE = GOALTYPECODE AND LOWER(GOALTYPE.GOALTYPE) = LOWER(GOAL) into GOALTYPEID;

SET ID = uuid();

INSERT INTO `USER`(ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, AGE, GENDER, WEIGHT, GOALTYPEID, LEVELOFFITNESS, USERTELEGRAMID, FRIENDTELEGRAMID) values (ID, FIRSTNAME, LASTNAME, PASSWORD, EMAIL, convert(AGE,UNSIGNED), GENDER, convert(WEIGHT,DOUBLE), GOALTYPEID, convert(LEVELOFFITNESS,unsigned), USERTELEGRAMID, FRIENDTELEGRAMID);

SELECT JSON_MERGE_PRESERVE(
       JSON_OBJECT('id', ID),
       JSON_OBJECT('first_name', FIRSTNAME),
       JSON_OBJECT('last_name', LASTNAME),
       JSON_OBJECT('name', CONCAT(FIRSTNAME,LASTNAME)),
       JSON_OBJECT('email', EMAIL),
       JSON_OBJECT('age', AGE),
       JSON_OBJECT('gender', GENDER),
       JSON_OBJECT('weight', WEIGHT),
       JSON_OBJECT('goal', GOALTYPECODE),
       JSON_OBJECT('goal_name', GOAL),
       JSON_OBJECT('level_of_fitness', LEVELOFFITNESS),
       JSON_OBJECT('telegram_ID_user', USERTELEGRAMID),
       JSON_OBJECT('telegram_ID_friend', FRIENDTELEGRAMID)
    ) INTO OUTPUT;

END
//
DELIMITER ;