USE db_101;

DROP PROCEDURE IF EXISTS USP_SAVE_TRIP;
DELIMITER //
CREATE PROCEDURE USP_SAVE_TRIP(
IN USERID VARCHAR (36),
IN `DATETIME` datetime,
IN AVERAGESPEED DOUBLE,
IN AVERAGEHEARTRATE DOUBLE,
IN MAXSPEED DOUBLE,
IN MAXHEARTRATE DOUBLE,
IN MINHEARTRATE DOUBLE,
IN HEARTRATEPLOT nvarchar(2083),
IN SPEEDPLOT nvarchar(2083),
IN MAP nvarchar(2083)
)
BEGIN

DECLARE ID VARCHAR(36);

SET ID = uuid();

INSERT INTO TRIP
(ID, USERID, `DATETIME`, AVERAGESPEED, AVERAGEHEARTRATE, MAXSPEED, MAXHEARTRATE, MINHEARTRATE, HEARTRATEPLOT, SPEEDPLOT, MAP) 
values 
(ID, USERID, `DATETIME`, AVERAGESPEED, AVERAGEHEARTRATE, MAXSPEED, MAXHEARTRATE, MINHEARTRATE, HEARTRATEPLOT, SPEEDPLOT, MAP);


END
//
DELIMITER ;