USE db_101;

DROP PROCEDURE IF EXISTS USP_GET_BIKEDETAILS;
DELIMITER //
CREATE PROCEDURE USP_GET_BIKEDETAILS(
IN BIKEID VARCHAR (36),
OUT OUTPUT JSON
)
BEGIN
DECLARE VALIDBIKE BOOL;

SET VALIDBIKE = 0;

SELECT 1 FROM BIKE WHERE BIKE.ID = BIKEID into VALIDBIKE;

IF VALIDBIKE = 1 AND BIKEID IS NOT NULL THEN
      SELECT JSON_MERGE_PRESERVE(
       JSON_OBJECT('id', ID),
       JSON_OBJECT('broker', BROKER),
       JSON_OBJECT('port_number', PORTNUMBER),
       JSON_OBJECT('url', URL)
    ) FROM BIKE WHERE BIKE.ID = BIKEID INTO OUTPUT;
ELSE
      SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Bike Not Found';
END IF;

END
//
DELIMITER ;