USE db_101;

DROP PROCEDURE IF EXISTS USP_GET_USER;
DELIMITER //
CREATE PROCEDURE USP_GET_USER(
 IN USERID varchar(36),
 OUT OUTPUT JSON
)
BEGIN
DECLARE VALIDUSER BOOL;
DECLARE USERID varchar(36);

SET VALIDUSER = 0;


SELECT  1 FROM `USER` WHERE `USER`.ID = USERID INTO VALIDUSER;

IF VALIDUSER = 1 AND USERID IS NOT NULL THEN
      SELECT JSON_MERGE_PRESERVE(
       JSON_OBJECT('id', `USER`.ID),
       JSON_OBJECT('first_name', FIRSTNAME),
       JSON_OBJECT('last_name', LASTNAME),
       JSON_OBJECT('name', CONCAT(FIRSTNAME,LASTNAME)),
       JSON_OBJECT('email', EMAIL),
       JSON_OBJECT('age', AGE),
       JSON_OBJECT('gender', GENDER),
       JSON_OBJECT('weight', WEIGHT),
       JSON_OBJECT('goal', GOALTYPE.GOALTYPECODE),
       JSON_OBJECT('goal_name', GOALTYPE.GOALTYPE),
       JSON_OBJECT('level_of_fitness', LEVELOFFITNESS),
       JSON_OBJECT('telegram_ID_user', USERTELEGRAMID),
       JSON_OBJECT('telegram_ID_friend', FRIENDTELEGRAMID)
    ) FROM `USER` inner join GOALTYPE on GOALTYPE.ID =  `USER`.GOALTYPEID
    WHERE `USER`.ID = USERID INTO OUTPUT;
      SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'User Not Found';
END IF;

END
//
DELIMITER ;